version: '3.8'
services:
    db:
        image: postgres:14
        container_name: wallet_db
        restart: always
        environment:
            POSTGRES_USER: wallet_user
            POSTGRES_PASSWORD: wallet_pass
            POSTGRES_DB: wallet_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/postgres_data

volumes:
    postgres_data: